/*
 * Connect API
 *
 * Service for interacting with Connection Manager resources
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Basic Auth Config message
type ConnectorBasicAuthConfig struct {
	// The key from the key-value pair in the consumer config that maps to the username example: consumer_config.username
	ConsumerConfigUsername string `json:"consumer_config_username,omitempty"`
	// The key from the key-value pair in the consumer config that maps to the password example: consumer_config.password
	ConsumerConfigPassword string `json:"consumer_config_password,omitempty"`
}
