/*
 * Connect API
 *
 * Service for interacting with Connection Manager resources
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Data to be used in the embedded marketplace to present the consumer with a UI to link a connector
type LoadConnectorLinkResponse struct {
	ConnectorLink *ConnectorLink `json:"connector_link,omitempty"`
	// consumer token for accessing Kolla API's as a consumer
	ConsumerToken string `json:"consumer_token,omitempty"`
}
