/*
 * Connect API
 *
 * Service for interacting with Connection Manager resources
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// API Key Config message
type ConnectorApiKeyConfig struct {
	// The key from the key-value pair in the consumer config that maps to the API key example: consumer_config.api_key
	ConsumerConfigKey string `json:"consumer_config_key,omitempty"`
	// Name of the query parameter field or header for the API key
	ParameterField string `json:"parameter_field,omitempty"`
	// whether the API key is in the query parameter or header
	Header bool `json:"header,omitempty"`
	// Prefix that should be added to the API key, sometimes 'Bearer ' is used as a prefix in authorization headers
	Prefix string `json:"prefix,omitempty"`
}
