/*
 * Connect API
 *
 * Service for interacting with Connection Manager resources
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// consumer metadata
type ConsumerMetadata struct {
	// consumer title, name of the person or organization the consumer_id is associated with
	Title string `json:"title,omitempty"`
	// email of the consumer
	Email string `json:"email,omitempty"`
}
