/*
 * Connect API
 *
 * Service for interacting with Connection Manager resources
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Token associated with the LinkedAccount
type CredentialsResponse struct {
	Credentials   *CredentialsResponseCredentials `json:"credentials,omitempty"`
	LinkedAccount *LinkedAccount                  `json:"linked_account,omitempty"`
}
