/*
 * Connect API
 *
 * Service for interacting with Connection Manager resources
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// consumer metadata
type ConsumerTokenRequestConsumerMetadata struct {
	// username of the consumer
	Username string `json:"username,omitempty"`
	// email of the consumer
	Email string `json:"email,omitempty"`
	// tenant_id of the consumer
	TenantId string `json:"tenant_id,omitempty"`
	// tenant_display_name of the consumer
	TenantDisplayName string `json:"tenant_display_name,omitempty"`
}
