/*
 * Connect API
 *
 * Service for interacting with Connection Manager resources
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Message for linked account credentials
type LinkedAccountCredentialsResponseCredentials struct {
	// LinkedAccount access token
	Token string `json:"token,omitempty"`
	// timestamp for when a new token should be requested
	ExpiryTime time.Time `json:"expiry_time,omitempty"`
}
