/*
 * Connect API
 *
 * Service for interacting with Connection Manager resources
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// On prem agent configuration
type ConnectorAgentConfig struct {
	// subscriber specific proxy_uri to reach the agent
	ProxyUri string `json:"proxy_uri,omitempty"`
}
