/*
 * Connect API
 *
 * Service for interacting with Connection Manager resources
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Request for a connector link
type LoadConnectorLinkRequest struct {
	// connector link id, not the full name
	ConnectorLinkId string `json:"connector_link_id"`
}
