/*
 * Connect API
 *
 * Service for interacting with Connection Manager resources
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

// Message for linked account credentials
type CredentialsResponseCredentials struct {
	// LinkedAccount access token, if available
	Token string `json:"token,omitempty"`
	// timestamp for when a new token should be requested
	ExpiryTime time.Time `json:"expiry_time,omitempty"`
	// secret key value pairs, available keys depend on the connector type. Basic auth connectors will have a username and password. OAuth2 and most APIKey connectors will not have any secrets
	Secrets map[string]string `json:"secrets,omitempty"`
}
