/*
 * Connect API
 *
 * Service for interacting with Connection Manager resources
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Returns the linked account's access token
type LinkedAccountCredentialsRequest struct {
	// LinkedAccount name
	LinkedAccount string `json:"linked_account,omitempty"`
	// consumer_id, if specified, will ensure that the LinkedAccount is owner by the given consumer if a wildcard '-' is used for the LinkedAccount_id, this field is required
	ConsumerId string `json:"consumer_id,omitempty"`
}
