/*
 * Connect API
 *
 * Service for interacting with Connection Manager resources
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Connector Template Resource
type ConnectorTemplate struct {
	// Resource name of the connector
	Name string `json:"name,omitempty"`
	// The system ID of the resource
	Uid string `json:"uid,omitempty"`
	// Short name that can be used to identify the connector in place of using the ID
	Slug string `json:"slug,omitempty"`
	// The manifest of the connector template
	Manifest *interface{} `json:"manifest,omitempty"`
}
