/*
 * Connect API
 *
 * Service for interacting with Connection Manager resources
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Request to disable linked account
type DisableLinkedAccountRequest struct {
	// The name of the linked account to disable Format: connectors/{connector}/linkedaccounts/{linkedaccount}
	Name string `json:"name"`
}
