/*
 * Connect API
 *
 * Service for interacting with Connection Manager resources
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Agent auth data is set when the connector type is AGENT
type LinkedAccountAgentAuthData struct {
	// agent install token used to linked back to the agent running on the customer's infrastructure
	InstallToken string `json:"install_token"`
	// agent name
	Agent string `json:"agent,omitempty"`
}
