name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Go build, test, vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        name: Set up Go
        with:
          go-version: 1.19

      - uses: actions/cache@v3
        name: Set up cache
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Vet
        run: go vet ./...

      - name: Run go generate and check for changes
        run: |
          if [ ! -f generate.sh ]
          then
              exit
          fi

          ./generate.sh
          diff=$(git status --porcelain)
          if [[ -z $diff ]];
          then
            echo "No changes"
          else
            echo "Changes detected"
            echo $diff
            exit 1;
          fi
